name: Validate Pull Request

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commitsar check
        uses: aevea/commitsar@916c7b483225a30d3a17f407fa25f5b25888ea69

      - uses: php-actions/composer@v6
        with:
          command: validate
          version: 2.8.1
